# Generated by Django 6.0.5 on 2026-05-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('groceries', 'Groceries'), ('technology', 'Technology'), ('clothing', 'Clothing'), ('beverages', 'Beverages'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('frozen', 'Frozen Foods'), ('snacks', 'Snacks'), ('household', 'Household'), ('personal', 'Personal Care'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
